import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../styles/globals.css";

const geistSans = Geist ({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono ({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Recipe a Day",
  description: "Generated by create next app",
  icons: {
    icon: "/pan16X16.png",
  },
};

export default function RootLayout ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">

      <head>

        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Righteous&display=swap"/>
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Russo+One&display=swap"/>
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Patrick+Hand&display=swap"/>
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Dekko&display=swap"/>

      </head>

      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {children}
      </body>

    </html>
  );
}
